/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InfosRouteImport } from './routes/infos'
import { Route as PrestationsRouteImport } from './routes/prestations'
import { Route as VaccinsRouteImport } from './routes/vaccins'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InfosRoute = InfosRouteImport.update({
  id: '/infos',
  path: '/infos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestationsRoute = PrestationsRouteImport.update({
  id: '/prestations',
  path: '/prestations',
  getParentRoute: () => rootRouteImport,
} as any)
const VaccinsRoute = VaccinsRouteImport.update({
  id: '/vaccins',
  path: '/vaccins',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/infos': typeof InfosRoute
  '/prestations': typeof PrestationsRoute
  '/vaccins': typeof VaccinsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/infos': typeof InfosRoute
  '/prestations': typeof PrestationsRoute
  '/vaccins': typeof VaccinsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/infos': typeof InfosRoute
  '/prestations': typeof PrestationsRoute
  '/vaccins': typeof VaccinsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/infos' | '/prestations' | '/vaccins'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/infos' | '/prestations' | '/vaccins'
  id: '__root__' | '/' | '/infos' | '/prestations' | '/vaccins'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InfosRoute: typeof InfosRoute
  PrestationsRoute: typeof PrestationsRoute
  VaccinsRoute: typeof VaccinsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infos': {
      id: '/infos'
      path: '/infos'
      fullPath: '/infos'
      preLoaderRoute: typeof InfosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestations': {
      id: '/prestations'
      path: '/prestations'
      fullPath: '/prestations'
      preLoaderRoute: typeof PrestationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaccins': {
      id: '/vaccins'
      path: '/vaccins'
      fullPath: '/vaccins'
      preLoaderRoute: typeof VaccinsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InfosRoute: InfosRoute,
  PrestationsRoute: PrestationsRoute,
  VaccinsRoute: VaccinsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
